spring:
  application:
    name: tracker-platform

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    from: ${MAIL_FROM:${MAIL_USERNAME:your-email@gmail.com}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
      name: ps-tomcat-jdbc
      validation-query: select 1
      test-on-borrow: true
      removeAbandoned: true
      removeAbandonedTimeout: 3600
      logAbandoned: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    create-schemas: true
    default-schema: public
    schemas: public
    validate-migration-naming: true

  sql:
    init:
      mode: always

  springdoc:
    api-docs:
      path: /api-docs
    packages-to-scan: hr.tvz.trackerplatform
    swagger-ui:
      path: /swagger-ui.html
      default-models-expand-depth: -1
      syntaxHighlight:
        activated: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

application:
  security:
    jwt:
      secret-key: ZjMzYzM4NzYzMTg0OWE4ZTY5M2ZlYjZhMDIyMjA4ZGQzYTNlZmQ4ZmU0MzU3ZThhNTc1Yzg1NTZiYzEyY2VlNzM5ZGM2MjdkMGY5NWMyY2Y5NmRiMDg3ZGFkOTM3NWEwODA5ODJjZWQ3NGI0MDdiMzZmYzlhOGU0NTEyODFmYzg=
      access-token-expiration: 300000
      refresh-token-expiration: 28800000
      reset-password-token-expiration: 900000

scheduler:
  cron:
    daily-check: "0 0 8 * * ?"
    habit-completion-fill: "0 0 0/8 * * ?"
    habit-streak-adjust: "0 0 0/12 * * ?"
    habit-streak-warning: "0 0 18 * * ?"
