spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

  mail:
    host: localhost
    port: 1026
    username: test
    password: test
    from: noreply@trackerplatform.com
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
    use-mock: false

frontend:
  url: http://localhost:4200

scheduler:
  cron:
    daily-check: "0 * * * * ?"
    habit-completion-fill: "0 0 0/8 * * ?"
    habit-streak-adjust: "0 0 0/12 * * ?"
    habit-streak-warning: "0 0 18 * * ?"
