name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '24.0.1'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Build application
        run: ./gradlew build
