name: CI/CD Pipeline

on:
  push:
    branches:
      - '**' # Run for pushes to any branch
  pull_request:
    branches:
      - '**' # Run for pull requests to any branch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pull-requests: write # Required for SonarCloud PR decoration
  checks: write # Required for updating checks on PRs

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    needs: test
    name: Build and Analyze
    uses: ./.github/workflows/build.yml
    secrets: inherit
