name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarQube to analyze git history

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "24"
          distribution: "corretto"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clear Gradle cache
        run: rm -rf ~/.gradle/caches/

      - name: Run tests
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        run: ./gradlew test --no-daemon --enable-native-access=ALL-UNNAMED
